In [1]:
import numpy as np

In [2]:
A = np.random.randint(0, 10, [2,3])
B = np.random.randint(1, 20, [2,3])

In [3]:
A

array([[3, 6, 0],
       [8, 6, 3]])

In [4]:
B

array([[18, 14, 15],
       [ 4, 19,  9]])

In [7]:
C = A + B

In [8]:
C

array([[21, 20, 15],
       [12, 25, 12]])