In [2]:
import numpy as np
import random as rd

In [17]:
tab = np.array([[1,2,3,6,5], [range(5)]])

In [20]:
tab

array([list([1, 2, 3, 6, 5]), list([range(0, 5)])], dtype=object)

In [19]:
tab.shape

(2,)

In [16]:
tab.ndim

1

In [21]:
tab_1 = np.zeros((2,3))

In [26]:
tab_1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
tab_1.ndim

2

In [23]:
tab_1.size

6

In [24]:
tab_2 = np.full((4,3), 26)

In [25]:
tab_2

array([[26, 26, 26],
       [26, 26, 26],
       [26, 26, 26],
       [26, 26, 26]])

In [32]:
np.random.seed(0)
tab_3 = np.random.randn(5,4)

In [33]:
tab_3

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [35]:
tab_4 = np.eye(3)

In [36]:
tab_4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
tab_5 = np.linspace(start=0, stop=10, num=20,dtype=np.float16)

In [64]:
tab_5

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [66]:
A = np.zeros((3,3))
B = np.ones((3,3))

In [68]:
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [69]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [70]:
abh = np.hstack((A,B))

In [71]:
abh

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [72]:
abv = np.vstack((A,B))

In [73]:
abv

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
contv = np.concatenate((A,B), axis=0)

In [75]:
contv

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
conth = np.concatenate((A, B), axis=1)

In [77]:
conth

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [78]:
contv.ndim

2

In [80]:
conth.ndim

2

In [81]:
contv.shape

(6, 3)

In [83]:
conth.shape

(3, 6)

In [84]:
autre = np.ones((1,1))

In [85]:
autre.shape

(1, 1)

In [86]:
autre.squeeze()

array(1.)

In [87]:
autre.shape

(1, 1)